<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31661" started-at="2021-05-24T07:10:06Z" finished-at="2021-05-24T07:10:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31661" started-at="2021-05-24T07:10:06Z" finished-at="2021-05-24T07:10:38Z">
      <class name="com.tests.CrmEmailTestScripts">
        <test-method status="PASS" signature="init()[pri:0, instance:com.tests.CrmEmailTestScripts@7225790e]" name="init" is-config="true" duration-ms="4040" started-at="2021-05-24T12:40:06Z" finished-at="2021-05-24T12:40:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="emailTestWithAttachment()[pri:0, instance:com.tests.CrmEmailTestScripts@7225790e]" name="emailTestWithAttachment" duration-ms="27600" started-at="2021-05-24T12:40:10Z" description="Send Email with To,Cc,Bcc,Subject along with Attachments" finished-at="2021-05-24T12:40:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Flowchart for an hospital appointmen.jpg] but found [Flowchart for an hospital appointment.jpg]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Flowchart for an hospital appointmen.jpg] but found [Flowchart for an hospital appointment.jpg]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.crm.validators.CrmEmailValidator.validateAttachmentOfEmail(CrmEmailValidator.java:21)
	at com.tests.CrmEmailTestScripts.emailTestWithAttachment(CrmEmailTestScripts.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- emailTestWithAttachment -->
      </class> <!-- com.tests.CrmEmailTestScripts -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
